name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - any-listen

permissions:
  contents: write

env:
  IS_CI: true
  SKIP_LIB_COPY: true

jobs:
  CheckTag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check_tag.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: 'true'
        fetch-tags: true

    - name: Check if submodule latest commit has a tag
      id: check_tag
      run: |
        cd any-listen
        latest_commit=$(git log -1 --format=%H)
        tag=$(git tag --contains "$latest_commit" | grep '^desktop-' | head -n 1)

        if [ -z "$tag" ]; then
          echo "No matching desktop tag found for the latest commit."
          echo "tag=" >> $GITHUB_OUTPUT
        else
          echo "Tag found for the latest commit: $tag, commit: $latest_commit"
          tag_formated=$(echo "$tag" | sed 's/^desktop-v\?//')
          echo "tag=$tag_formated" >> $GITHUB_OUTPUT
        fi
  CreateTag:
    needs: CheckTag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_tag.outputs.tag }}
    if: needs.CheckTag.outputs.tag != ''
    steps:
      - name: Create git tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ needs.CheckTag.outputs.tag }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Output tag
        id: create_tag
        run: |
          echo "tag=${{ needs.CheckTag.outputs.tag }}" >> $GITHUB_OUTPUT

  BuildWindows:
    needs: CreateTag
    name: Build Windows
    runs-on: windows-latest
    outputs:
      shasum: ${{ steps.win_shasum.outputs.shasum }}
    if: needs.CreateTag.outputs.tag != ''
    steps:
      - name: Check out git repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd any-listen
          corepack enable && pnpm install --frozen-lockfile

      - name: Build src code
        run: |
          cd any-listen
          pnpm -F scripts build:desktop

      - name: Build packages
        run: |
          cd any-listen
          pnpm -F scripts publish:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file SHA256
        id: win_shasum
        run: |
          cd any-listen/build
          $hashes = Get-FileHash *.exe,*.7z -Algorithm SHA256 | ForEach-Object {
            "$($_.Hash)  $($_.Path | Split-Path -Leaf)"
          }
          $hashes | Out-String
          echo "shasum<<EOF" >> $env:GITHUB_OUTPUT
          $hashes | ForEach-Object { echo "$_" >> $env:GITHUB_OUTPUT }
          echo "EOF" >> $env:GITHUB_OUTPUT

  BuildWindowsLegacy:
    needs: CreateTag
    name: Build Windows Legacy
    runs-on: windows-latest
    outputs:
      shasum: ${{ steps.win_legacy_shasum.outputs.shasum }}
    if: needs.CreateTag.outputs.tag != ''
    steps:
      - name: Check out git repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd any-listen
          corepack enable && pnpm install --frozen-lockfile

      - name: Prepare win_legacy undici env
        run: |
          pnpm -F @shared/nodejs add undici@5
          Set-Content -Path .\any-listen\packages\shared\nodejs\request.ts -Value "export * from './request_node16'"

      - name: Build src code
        env:
          BUILD_WIN_LEGACY: true
        run: |
          cd any-listen
          pnpm -F scripts build:desktop

      - name: Prepare win_legacy electron env
        run: |
          pnpm -F desktop add electron@22
          pip.exe install setuptools

      - name: Release win_legacy package
        run: |
          cd any-listen
          pnpm -F scripts publish:win_legacy

      - name: Upload win_legacy package to release
        uses: softprops/action-gh-release@v2.5.0
        with:
          draft: true
          tag_name: v${{ needs.CreateTag.outputs.tag }}
          files: |
            any-listen/build/*.exe
            any-listen/build/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file SHA256
        id: win_legacy_shasum
        run: |
          cd any-listen/build
          $hashes = Get-FileHash *.exe,*.7z -Algorithm SHA256 | ForEach-Object {
            "$($_.Hash)  $($_.Path | Split-Path -Leaf)"
          }
          $hashes | Out-String
          echo "shasum<<EOF" >> $env:GITHUB_OUTPUT
          $hashes | ForEach-Object { echo "$_" >> $env:GITHUB_OUTPUT }
          echo "EOF" >> $env:GITHUB_OUTPUT

  BuildMac:
    needs: CreateTag
    name: Build Mac
    runs-on: macos-latest
    outputs:
      shasum: ${{ steps.mac_shasum.outputs.shasum }}
    if: needs.CreateTag.outputs.tag != ''
    steps:
      - name: Install python3 setuptools
        run: brew install python-setuptools

      - name: Check out git repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd any-listen
          corepack enable && pnpm install --frozen-lockfile

      - name: Build src code
        run: |
          cd any-listen
          pnpm -F scripts build:desktop

      - name: Build packages
        run: |
          cd any-listen
          pnpm -F scripts publish:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file SHA256
        id: mac_shasum
        run: |
          cd any-listen/build
          hashes=$(shasum -a 256 *.dmg *.zip)
          echo "$hashes"
          echo "shasum<<EOF" >> $GITHUB_OUTPUT
          echo "$hashes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  BuildLinux:
    needs: CreateTag
    name: Build Linux
    runs-on: ubuntu-latest
    outputs:
      shasum: ${{ steps.linux_shasum.outputs.shasum }}
    if: needs.CreateTag.outputs.tag != ''
    steps:
      - name: Install package
        run: sudo apt-get update && sudo apt-get install -y rpm libarchive-tools

      - name: Check out git repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd any-listen
          corepack enable && pnpm install --frozen-lockfile

      - name: Build src code
        run: |
          cd any-listen
          pnpm -F scripts build:desktop

      - name: Build packages
        run: |
          cd any-listen
          pnpm -F scripts publish:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate file SHA256
        id: linux_shasum
        run: |
          cd any-listen/build
          hashes=$(sha256sum *.deb *.rpm *.pacman *.AppImage)
          echo "$hashes"
          echo "shasum<<EOF" >> $GITHUB_OUTPUT
          echo "$hashes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  Release:
    needs:
      - CreateTag
      - BuildWindows
      - BuildWindowsLegacy
      - BuildMac
      - BuildLinux
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Set release variables
        id: set-release-vars
        run: |
          TAG="${{ needs.CreateTag.outputs.tag }}"
          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "TAG is not in x.x.x format. Using beta settings."
            echo "log_file=./any-listen/packages/desktop/publish/changeLog.beta.md" >> $GITHUB_ENV
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "TAG is in x.x.x format. Using regular release settings."
            echo "log_file=./any-listen/packages/desktop/publish/changeLog.md" >> $GITHUB_ENV
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Collect SHA256SUMS
        run: |
          {
            echo "${{ needs.BuildWindows.outputs.shasum }}"
            echo "${{ needs.BuildWindowsLegacy.outputs.shasum }}"
            echo "${{ needs.BuildMac.outputs.shasum }}"
            echo "${{ needs.BuildLinux.outputs.shasum }}"
          } > SHA256SUMS.txt
          echo "" >> ${{ env.log_file }}
          echo "### File SHA256SUMS" >> ${{ env.log_file }}
          echo '```' >> ${{ env.log_file }}
          cat SHA256SUMS.txt >> ${{ env.log_file }}
          echo '```' >> ${{ env.log_file }}
          echo "" >> ${{ env.log_file }}

      - name: Release
        # https://github.com/softprops/action-gh-release/issues/772
        uses: softprops/action-gh-release@v2.5.0
        with:
          body_path: ${{ env.log_file }}
          prerelease: ${{ env.prerelease }}
          draft: false
          tag_name: v${{ needs.CreateTag.outputs.tag }}
          files: |
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
